"""Add missing dark mode color fields to app_settings

Revision ID: 10c64b68ff24
Revises: fd4bbc9bd573
Create Date: 2025-12-08 19:46:08.766104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10c64b68ff24"
down_revision: Union[str, None] = "fd4bbc9bd573"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_settings",
        sa.Column("dark_primary_subtle_color", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "app_settings",
        sa.Column("dark_success_color", sa.String(length=7), nullable=True),
    )
    op.add_column(
        "app_settings",
        sa.Column("dark_success_bg_color", sa.String(length=7), nullable=True),
    )
    op.add_column(
        "app_settings",
        sa.Column("dark_danger_color", sa.String(length=7), nullable=True),
    )
    op.add_column(
        "app_settings",
        sa.Column("dark_danger_bg_color", sa.String(length=7), nullable=True),
    )
    op.add_column(
        "app_settings",
        sa.Column("dark_warning_color", sa.String(length=7), nullable=True),
    )
    op.add_column(
        "app_settings",
        sa.Column("dark_warning_bg_color", sa.String(length=7), nullable=True),
    )
    op.add_column(
        "app_settings", sa.Column("dark_info_color", sa.String(length=7), nullable=True)
    )
    op.add_column(
        "app_settings",
        sa.Column("dark_info_bg_color", sa.String(length=7), nullable=True),
    )
    op.add_column(
        "app_settings",
        sa.Column("dark_unknown_color", sa.String(length=7), nullable=True),
    )
    op.add_column(
        "app_settings",
        sa.Column("dark_unknown_bg_color", sa.String(length=7), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_settings", "dark_unknown_bg_color")
    op.drop_column("app_settings", "dark_unknown_color")
    op.drop_column("app_settings", "dark_info_bg_color")
    op.drop_column("app_settings", "dark_info_color")
    op.drop_column("app_settings", "dark_warning_bg_color")
    op.drop_column("app_settings", "dark_warning_color")
    op.drop_column("app_settings", "dark_danger_bg_color")
    op.drop_column("app_settings", "dark_danger_color")
    op.drop_column("app_settings", "dark_success_bg_color")
    op.drop_column("app_settings", "dark_success_color")
    op.drop_column("app_settings", "dark_primary_subtle_color")
    # ### end Alembic commands ###
