"""add_http_advanced_features

Revision ID: 28db2243365b
Revises: 54a270d5773c
Create Date: 2025-11-22 23:23:38.377662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28db2243365b"
down_revision: Union[str, Sequence[str], None] = "54a270d5773c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitor", sa.Column("http_method", sa.String(length=10), nullable=True)
    )
    op.add_column("monitor", sa.Column("http_headers", sa.Text(), nullable=True))
    op.add_column("monitor", sa.Column("http_body", sa.Text(), nullable=True))
    op.add_column("monitor", sa.Column("http_ssl_ca_cert", sa.Text(), nullable=True))
    op.add_column(
        "monitor", sa.Column("http_ssl_client_cert", sa.Text(), nullable=True)
    )
    op.add_column("monitor", sa.Column("http_ssl_client_key", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitor", "http_ssl_client_key")
    op.drop_column("monitor", "http_ssl_client_cert")
    op.drop_column("monitor", "http_ssl_ca_cert")
    op.drop_column("monitor", "http_body")
    op.drop_column("monitor", "http_headers")
    op.drop_column("monitor", "http_method")
    # ### end Alembic commands ###
