"""add_critical_performance_indexes

Revision ID: 2908373e6ce2
Revises: a10c12e51bcb
Create Date: 2025-12-02 23:41:19.308208

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2908373e6ce2"
down_revision: Union[str, None] = "a10c12e51bcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_recent_checks", "check_result", ["monitor_id", "timestamp"], unique=False
    )
    op.create_index(
        "idx_uptime_calculation",
        "check_result",
        ["monitor_id", "timestamp", "status"],
        unique=False,
    )
    op.create_index(
        "idx_monitor_dashboard_primary",
        "monitor",
        ["user_id", "is_active", "last_check", "name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_monitor_dashboard_primary", table_name="monitor")
    op.drop_index("idx_uptime_calculation", table_name="check_result")
    op.drop_index("idx_recent_checks", table_name="check_result")
    # ### end Alembic commands ###
