"""add_consecutive_failure_tracking

Revision ID: 54a270d5773c
Revises: 156027c76783
Create Date: 2025-11-22 20:55:43.948051

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54a270d5773c"
down_revision: Union[str, Sequence[str], None] = "156027c76783"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitor", sa.Column("consecutive_failures", sa.Integer(), nullable=True)
    )
    op.add_column(
        "monitor_notification",
        sa.Column("consecutive_checks_threshold", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitor_notification", "consecutive_checks_threshold")
    op.drop_column("monitor", "consecutive_failures")
    # ### end Alembic commands ###
