"""Add OIDC authentication support

Revision ID: 579ac7ed1c53
Revises: fc8f47027f1b
Create Date: 2025-12-12 22:20:52.771079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "579ac7ed1c53"
down_revision: Union[str, None] = "fc8f47027f1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oidc_provider",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("issuer_url", sa.String(length=500), nullable=True),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("client_secret", sa.String(length=255), nullable=False),
        sa.Column("auth_url", sa.String(length=500), nullable=True),
        sa.Column("token_url", sa.String(length=500), nullable=True),
        sa.Column("jwks_url", sa.String(length=500), nullable=True),
        sa.Column("userinfo_url", sa.String(length=500), nullable=True),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oidc_provider_name"), "oidc_provider", ["name"], unique=True
    )

    # Use batch mode for SQLite to modify user table
    with op.batch_alter_table("user") as batch_op:
        batch_op.add_column(sa.Column("auth_type", sa.String(length=20), nullable=True))
        batch_op.add_column(
            sa.Column("oidc_provider", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("oidc_subject", sa.String(length=255), nullable=True)
        )
        batch_op.alter_column(
            "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    # Update existing users to have auth_type='local'
    op.execute("UPDATE user SET auth_type='local' WHERE auth_type IS NULL")

    # SQLite doesn't support making columns NOT NULL after adding them, so we'll skip this step
    # The auth_type will have a default value in the model and existing users will be set to 'local'

    op.create_index(
        "idx_oidc_identity", "user", ["oidc_provider", "oidc_subject"], unique=False
    )
    op.create_index(op.f("ix_user_auth_type"), "user", ["auth_type"], unique=False)
    op.create_index(
        op.f("ix_user_oidc_provider"), "user", ["oidc_provider"], unique=False
    )
    op.create_index(
        op.f("ix_user_oidc_subject"), "user", ["oidc_subject"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_oidc_subject"), table_name="user")
    op.drop_index(op.f("ix_user_oidc_provider"), table_name="user")
    op.drop_index(op.f("ix_user_auth_type"), table_name="user")
    op.drop_index("idx_oidc_identity", table_name="user")
    op.alter_column(
        "user", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("user", "oidc_subject")
    op.drop_column("user", "oidc_provider")
    op.drop_column("user", "auth_type")
    op.drop_index(op.f("ix_oidc_provider_name"), table_name="oidc_provider")
    op.drop_table("oidc_provider")
    # ### end Alembic commands ###
