"""fix_oidc_provider_column_names

Revision ID: 6fee1ec26f10
Revises: 6c9d8cd6c81c
Create Date: 2025-12-13 21:48:33.738049

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6fee1ec26f10"
down_revision: Union[str, None] = "6c9d8cd6c81c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to manually handle the data migration since batch mode doesn't work well with complex operations
    # First, create a new table with the correct schema
    op.execute("""
        CREATE TABLE oidc_provider_new (
            id INTEGER PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            display_name VARCHAR(100) NOT NULL,
            issuer_url VARCHAR(500),
            client_id VARCHAR(255) NOT NULL,
            client_secret VARCHAR(255) NOT NULL,
            auth_url VARCHAR(500),
            token_url VARCHAR(500),
            jwks_url VARCHAR(500),
            userinfo_url VARCHAR(500),
            scope VARCHAR(200) NOT NULL,
            is_active BOOLEAN NOT NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL
        )
    """)

    # Copy data from old table to new table with column name mapping
    op.execute("""
        INSERT INTO oidc_provider_new (
            id, name, display_name, issuer_url, client_id, client_secret,
            auth_url, token_url, jwks_url, userinfo_url, scope, is_active,
            created_at, updated_at
        )
        SELECT
            id, name, display_name, issuer_url, client_id, client_secret,
            authorization_endpoint, token_endpoint, jwks_uri, userinfo_endpoint,
            scope, is_active, created_at, updated_at
        FROM oidc_provider
    """)

    # Drop the old table
    op.drop_table("oidc_provider")

    # Rename the new table to the original name
    op.execute("ALTER TABLE oidc_provider_new RENAME TO oidc_provider")

    # Recreate indexes
    op.create_index(
        op.f("ix_oidc_provider_name"), "oidc_provider", ["name"], unique=True
    )

    # Update user table
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column("password_hash", nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the original table structure
    op.execute("""
        CREATE TABLE oidc_provider_old (
            id INTEGER PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            display_name VARCHAR(100) NOT NULL,
            issuer_url VARCHAR(500),
            client_id VARCHAR(255) NOT NULL,
            client_secret VARCHAR(255),
            authorization_endpoint VARCHAR(500),
            token_endpoint VARCHAR(500),
            userinfo_endpoint VARCHAR(500),
            jwks_uri VARCHAR(500),
            scope VARCHAR(100) NOT NULL DEFAULT 'openid profile email',
            is_active BOOLEAN NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Copy data from current table back to old schema
    op.execute("""
        INSERT INTO oidc_provider_old (
            id, name, display_name, issuer_url, client_id, client_secret,
            authorization_endpoint, token_endpoint, userinfo_endpoint, jwks_uri,
            scope, is_active, created_at, updated_at
        )
        SELECT
            id, name, display_name, issuer_url, client_id, client_secret,
            auth_url, token_url, userinfo_url, jwks_url,
            scope, is_active, created_at, updated_at
        FROM oidc_provider
    """)

    # Drop the current table
    op.drop_table("oidc_provider")

    # Rename the old table back to original name
    op.execute("ALTER TABLE oidc_provider_old RENAME TO oidc_provider")

    # Recreate the original indexes
    op.create_index(
        op.f("ix_oidc_provider_name"), "oidc_provider", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_oidc_provider_is_active"), "oidc_provider", ["is_active"], unique=False
    )

    # Restore user table
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column("password_hash", nullable=False)
    # ### end Alembic commands ###
