"""initial schema

Revision ID: 73d2db348c9b
Revises:
Create Date: 2025-11-30 22:56:34.047731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73d2db348c9b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_level", sa.String(length=20), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("data_retention_days", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "domain_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain_hash", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=500), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("dns_info", sa.Text(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_domain_hash", "domain_info", ["domain_hash"], unique=False)
    op.create_index("idx_domain_name", "domain_info", ["domain"], unique=False)
    op.create_index("idx_domain_usage", "domain_info", ["usage_count"], unique=False)
    op.create_index(
        op.f("ix_domain_info_domain"), "domain_info", ["domain"], unique=True
    )
    op.create_index(
        op.f("ix_domain_info_domain_hash"), "domain_info", ["domain_hash"], unique=True
    )
    op.create_table(
        "error_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_hash", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_error_message_hash", "error_messages", ["message_hash"], unique=False
    )
    op.create_index(
        "idx_error_message_usage", "error_messages", ["usage_count"], unique=False
    )
    op.create_index(
        op.f("ix_error_messages_message_hash"),
        "error_messages",
        ["message_hash"],
        unique=True,
    )
    op.create_table(
        "tls_certificates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cert_hash", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=500), nullable=False),
        sa.Column("cert_data", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tls_cert_domain", "tls_certificates", ["domain"], unique=False)
    op.create_index(
        "idx_tls_cert_expires", "tls_certificates", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_tls_cert_hash", "tls_certificates", ["cert_hash"], unique=False
    )
    op.create_index(
        "idx_tls_cert_usage", "tls_certificates", ["usage_count"], unique=False
    )
    op.create_index(
        op.f("ix_tls_certificates_cert_hash"),
        "tls_certificates",
        ["cert_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_tls_certificates_domain"), "tls_certificates", ["domain"], unique=False
    )
    op.create_index(
        op.f("ix_tls_certificates_expires_at"),
        "tls_certificates",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "monitor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "type",
            sa.Enum("HTTP", "HTTPS", "TCP", "PING", "KAFKA", name="monitortype"),
            nullable=False,
        ),
        sa.Column("target", sa.String(length=500), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column(
            "check_interval",
            sa.Enum(
                "THIRTY_SECONDS",
                "ONE_MINUTE",
                "FIVE_MINUTES",
                "FIFTEEN_MINUTES",
                "THIRTY_MINUTES",
                "ONE_HOUR",
                name="checkinterval",
            ),
            nullable=False,
        ),
        sa.Column("timeout", sa.Integer(), nullable=True),
        sa.Column("expected_status_codes", sa.Text(), nullable=True),
        sa.Column("response_time_threshold", sa.Integer(), nullable=True),
        sa.Column("string_match", sa.String(length=500), nullable=True),
        sa.Column("string_match_type", sa.String(length=20), nullable=True),
        sa.Column("json_path_match", sa.String(length=500), nullable=True),
        sa.Column("http_method", sa.String(length=10), nullable=True),
        sa.Column("http_headers", sa.Text(), nullable=True),
        sa.Column("http_body", sa.Text(), nullable=True),
        sa.Column("verify_ssl", sa.Boolean(), nullable=True),
        sa.Column("check_cert_expiration", sa.Boolean(), nullable=True),
        sa.Column("cert_expiration_threshold", sa.Integer(), nullable=True),
        sa.Column("http_ssl_ca_cert", sa.Text(), nullable=True),
        sa.Column("http_ssl_client_cert", sa.Text(), nullable=True),
        sa.Column("http_ssl_client_key", sa.Text(), nullable=True),
        sa.Column("check_domain", sa.Boolean(), nullable=True),
        sa.Column("expected_domain", sa.String(length=500), nullable=True),
        sa.Column("kafka_security_protocol", sa.String(length=20), nullable=True),
        sa.Column("kafka_sasl_mechanism", sa.String(length=20), nullable=True),
        sa.Column("kafka_sasl_username", sa.String(length=500), nullable=True),
        sa.Column("kafka_sasl_password", sa.String(length=500), nullable=True),
        sa.Column("kafka_oauth_token_url", sa.String(length=500), nullable=True),
        sa.Column("kafka_oauth_client_id", sa.String(length=500), nullable=True),
        sa.Column("kafka_oauth_client_secret", sa.String(length=500), nullable=True),
        sa.Column("kafka_ssl_ca_cert", sa.Text(), nullable=True),
        sa.Column("kafka_ssl_client_cert", sa.Text(), nullable=True),
        sa.Column("kafka_ssl_client_key", sa.Text(), nullable=True),
        sa.Column("kafka_topic", sa.String(length=500), nullable=True),
        sa.Column("kafka_consumer_group", sa.String(length=500), nullable=True),
        sa.Column("kafka_read_message", sa.Boolean(), nullable=True),
        sa.Column("kafka_write_message", sa.Boolean(), nullable=True),
        sa.Column("kafka_message_payload", sa.Text(), nullable=True),
        sa.Column("kafka_autocommit", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_check", sa.DateTime(), nullable=True),
        sa.Column("last_status", sa.String(length=20), nullable=True),
        sa.Column("last_response_time", sa.Float(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=True),
        sa.Column("last_tls_check", sa.DateTime(), nullable=True),
        sa.Column("last_domain_check", sa.DateTime(), nullable=True),
        sa.Column("domain_check_failed", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_monitor_type_active", "monitor", ["type", "is_active"], unique=False
    )
    op.create_index(
        "idx_monitor_user_active", "monitor", ["user_id", "is_active"], unique=False
    )
    op.create_index(
        op.f("ix_monitor_is_active"), "monitor", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_monitor_type"), "monitor", ["type"], unique=False)
    op.create_index(op.f("ix_monitor_user_id"), "monitor", ["user_id"], unique=False)
    op.create_table(
        "notification_channel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum("EMAIL", "TELEGRAM", "SLACK", name="notificationtype"),
            nullable=False,
        ),
        sa.Column("config", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("last_sent", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_channel_user_id"),
        "notification_channel",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "check_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("response_time", sa.Float(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("error_message_id", sa.Integer(), nullable=True),
        sa.Column("additional_data", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["error_message_id"],
            ["error_messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["monitor_id"],
            ["monitor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_check_result_error_message",
        "check_result",
        ["error_message_id"],
        unique=False,
    )
    op.create_index(
        "idx_check_result_monitor_timestamp",
        "check_result",
        ["monitor_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_check_result_response_time",
        "check_result",
        ["response_time"],
        unique=False,
    )
    op.create_index(
        "idx_check_result_status_timestamp",
        "check_result",
        ["status", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_check_result_error_message_id"),
        "check_result",
        ["error_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_check_result_monitor_id"), "check_result", ["monitor_id"], unique=False
    )
    op.create_index(
        op.f("ix_check_result_response_time"),
        "check_result",
        ["response_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_check_result_status"), "check_result", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_check_result_timestamp"), "check_result", ["timestamp"], unique=False
    )
    op.create_table(
        "incident",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitor_id"],
            ["monitor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_incident_monitor_started",
        "incident",
        ["monitor_id", "started_at"],
        unique=False,
    )
    op.create_index(
        "idx_incident_status_started",
        "incident",
        ["status", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_monitor_id"), "incident", ["monitor_id"], unique=False
    )
    op.create_index(
        op.f("ix_incident_resolved_at"), "incident", ["resolved_at"], unique=False
    )
    op.create_index(
        op.f("ix_incident_started_at"), "incident", ["started_at"], unique=False
    )
    op.create_index(op.f("ix_incident_status"), "incident", ["status"], unique=False)
    op.create_table(
        "monitor_notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("notify_on_down", sa.Boolean(), nullable=False),
        sa.Column("notify_on_up", sa.Boolean(), nullable=False),
        sa.Column("notify_on_ssl_warning", sa.Boolean(), nullable=False),
        sa.Column("consecutive_checks_threshold", sa.Integer(), nullable=True),
        sa.Column("escalate_after_minutes", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["notification_channel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["monitor_id"],
            ["monitor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("monitor_id", "channel_id", name="uq_monitor_channel"),
    )
    op.create_index(
        "idx_monitor_notification_channel",
        "monitor_notification",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        "idx_monitor_notification_monitor",
        "monitor_notification",
        ["monitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_notification_channel_id"),
        "monitor_notification",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_notification_monitor_id"),
        "monitor_notification",
        ["monitor_id"],
        unique=False,
    )
    op.create_table(
        "incident_check_results",
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("check_result_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["check_result_id"],
            ["check_result.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incident.id"],
        ),
        sa.PrimaryKeyConstraint("incident_id", "check_result_id"),
    )
    op.create_index(
        "idx_incident_check_result",
        "incident_check_results",
        ["incident_id", "check_result_id"],
        unique=False,
    )
    op.create_table(
        "notification_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("sent_successfully", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["notification_channel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incident.id"],
        ),
        sa.ForeignKeyConstraint(
            ["monitor_id"],
            ["monitor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notification_log_channel_sent",
        "notification_log",
        ["channel_id", "sent_at"],
        unique=False,
    )
    op.create_index(
        "idx_notification_log_monitor_sent",
        "notification_log",
        ["monitor_id", "sent_at"],
        unique=False,
    )
    op.create_index(
        "idx_notification_log_status",
        "notification_log",
        ["sent_successfully"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_log_channel_id"),
        "notification_log",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_log_incident_id"),
        "notification_log",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_log_monitor_id"),
        "notification_log",
        ["monitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_log_sent_at"),
        "notification_log",
        ["sent_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_log_sent_at"), table_name="notification_log")
    op.drop_index(op.f("ix_notification_log_monitor_id"), table_name="notification_log")
    op.drop_index(
        op.f("ix_notification_log_incident_id"), table_name="notification_log"
    )
    op.drop_index(op.f("ix_notification_log_channel_id"), table_name="notification_log")
    op.drop_index("idx_notification_log_status", table_name="notification_log")
    op.drop_index("idx_notification_log_monitor_sent", table_name="notification_log")
    op.drop_index("idx_notification_log_channel_sent", table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_index("idx_incident_check_result", table_name="incident_check_results")
    op.drop_table("incident_check_results")
    op.drop_index(
        op.f("ix_monitor_notification_monitor_id"), table_name="monitor_notification"
    )
    op.drop_index(
        op.f("ix_monitor_notification_channel_id"), table_name="monitor_notification"
    )
    op.drop_index("idx_monitor_notification_monitor", table_name="monitor_notification")
    op.drop_index("idx_monitor_notification_channel", table_name="monitor_notification")
    op.drop_table("monitor_notification")
    op.drop_index(op.f("ix_incident_status"), table_name="incident")
    op.drop_index(op.f("ix_incident_started_at"), table_name="incident")
    op.drop_index(op.f("ix_incident_resolved_at"), table_name="incident")
    op.drop_index(op.f("ix_incident_monitor_id"), table_name="incident")
    op.drop_index("idx_incident_status_started", table_name="incident")
    op.drop_index("idx_incident_monitor_started", table_name="incident")
    op.drop_table("incident")
    op.drop_index(op.f("ix_check_result_timestamp"), table_name="check_result")
    op.drop_index(op.f("ix_check_result_status"), table_name="check_result")
    op.drop_index(op.f("ix_check_result_response_time"), table_name="check_result")
    op.drop_index(op.f("ix_check_result_monitor_id"), table_name="check_result")
    op.drop_index(op.f("ix_check_result_error_message_id"), table_name="check_result")
    op.drop_index("idx_check_result_status_timestamp", table_name="check_result")
    op.drop_index("idx_check_result_response_time", table_name="check_result")
    op.drop_index("idx_check_result_monitor_timestamp", table_name="check_result")
    op.drop_index("idx_check_result_error_message", table_name="check_result")
    op.drop_table("check_result")
    op.drop_index(
        op.f("ix_notification_channel_user_id"), table_name="notification_channel"
    )
    op.drop_table("notification_channel")
    op.drop_index(op.f("ix_monitor_user_id"), table_name="monitor")
    op.drop_index(op.f("ix_monitor_type"), table_name="monitor")
    op.drop_index(op.f("ix_monitor_is_active"), table_name="monitor")
    op.drop_index("idx_monitor_user_active", table_name="monitor")
    op.drop_index("idx_monitor_type_active", table_name="monitor")
    op.drop_table("monitor")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_tls_certificates_expires_at"), table_name="tls_certificates")
    op.drop_index(op.f("ix_tls_certificates_domain"), table_name="tls_certificates")
    op.drop_index(op.f("ix_tls_certificates_cert_hash"), table_name="tls_certificates")
    op.drop_index("idx_tls_cert_usage", table_name="tls_certificates")
    op.drop_index("idx_tls_cert_hash", table_name="tls_certificates")
    op.drop_index("idx_tls_cert_expires", table_name="tls_certificates")
    op.drop_index("idx_tls_cert_domain", table_name="tls_certificates")
    op.drop_table("tls_certificates")
    op.drop_index(op.f("ix_error_messages_message_hash"), table_name="error_messages")
    op.drop_index("idx_error_message_usage", table_name="error_messages")
    op.drop_index("idx_error_message_hash", table_name="error_messages")
    op.drop_table("error_messages")
    op.drop_index(op.f("ix_domain_info_domain_hash"), table_name="domain_info")
    op.drop_index(op.f("ix_domain_info_domain"), table_name="domain_info")
    op.drop_index("idx_domain_usage", table_name="domain_info")
    op.drop_index("idx_domain_name", table_name="domain_info")
    op.drop_index("idx_domain_hash", table_name="domain_info")
    op.drop_table("domain_info")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
