"""add kafka_consumer_group field

Revision ID: 8f93f0f8383b
Revises: 28db2243365b
Create Date: 2025-11-24 21:15:15.045294

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f93f0f8383b"
down_revision: Union[str, Sequence[str], None] = "28db2243365b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitor",
        sa.Column("kafka_consumer_group", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitor", "kafka_consumer_group")
    # ### end Alembic commands ###
