"""Add composite indexes for performance optimization

Revision ID: a10c12e51bcb
Revises: 73d2db348c9b
Create Date: 2025-12-01 23:03:50.228745

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a10c12e51bcb"
down_revision: Union[str, None] = "73d2db348c9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_check_result_monitor_status_time",
        "check_result",
        ["monitor_id", "status", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_check_result_monitor_success_time",
        "check_result",
        ["monitor_id", "timestamp", "status"],
        unique=False,
    )
    op.create_index(
        "idx_check_result_time_status",
        "check_result",
        ["timestamp", "status"],
        unique=False,
    )
    op.create_index(
        "idx_incident_active_started",
        "incident",
        ["status", "started_at"],
        unique=False,
    )
    op.create_index(
        "idx_incident_monitor_status_started",
        "incident",
        ["monitor_id", "status", "started_at"],
        unique=False,
    )
    op.create_index(
        "idx_incident_resolved_started",
        "incident",
        ["resolved_at", "started_at"],
        unique=False,
    )
    op.create_index(
        "idx_monitor_active_status",
        "monitor",
        ["is_active", "last_status", "last_check"],
        unique=False,
    )
    op.create_index(
        "idx_monitor_consecutive_failures",
        "monitor",
        ["consecutive_failures", "is_active"],
        unique=False,
    )
    op.create_index(
        "idx_monitor_status_check_time",
        "monitor",
        ["last_status", "last_check"],
        unique=False,
    )
    op.create_index(
        "idx_monitor_user_active_updated",
        "monitor",
        ["user_id", "is_active", "updated_at"],
        unique=False,
    )
    op.create_index(
        "idx_monitor_user_name", "monitor", ["user_id", "name"], unique=False
    )
    op.create_index(
        "idx_monitor_user_type_active",
        "monitor",
        ["user_id", "type", "is_active"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_monitor_user_type_active", table_name="monitor")
    op.drop_index("idx_monitor_user_name", table_name="monitor")
    op.drop_index("idx_monitor_user_active_updated", table_name="monitor")
    op.drop_index("idx_monitor_status_check_time", table_name="monitor")
    op.drop_index("idx_monitor_consecutive_failures", table_name="monitor")
    op.drop_index("idx_monitor_active_status", table_name="monitor")
    op.drop_index("idx_incident_resolved_started", table_name="incident")
    op.drop_index("idx_incident_monitor_status_started", table_name="incident")
    op.drop_index("idx_incident_active_started", table_name="incident")
    op.drop_index("idx_check_result_time_status", table_name="check_result")
    op.drop_index("idx_check_result_monitor_success_time", table_name="check_result")
    op.drop_index("idx_check_result_monitor_status_time", table_name="check_result")
    # ### end Alembic commands ###
