"""Add PublicStatusPage model for public status pages

Revision ID: cc40503cb931
Revises: 2908373e6ce2
Create Date: 2025-12-06 16:31:48.041886

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc40503cb931"
down_revision: Union[str, None] = "2908373e6ce2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "public_status_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=100), nullable=False),
        sa.Column("url_type", sa.String(length=20), nullable=False),
        sa.Column("custom_header", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("selected_monitors", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_public_status_user_active",
        "public_status_pages",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "idx_public_status_uuid_active",
        "public_status_pages",
        ["uuid", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_public_status_pages_is_active"),
        "public_status_pages",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_public_status_pages_user_id"),
        "public_status_pages",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_public_status_pages_uuid"),
        "public_status_pages",
        ["uuid"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_status_pages_uuid"), table_name="public_status_pages")
    op.drop_index(
        op.f("ix_public_status_pages_user_id"), table_name="public_status_pages"
    )
    op.drop_index(
        op.f("ix_public_status_pages_is_active"), table_name="public_status_pages"
    )
    op.drop_index("idx_public_status_uuid_active", table_name="public_status_pages")
    op.drop_index("idx_public_status_user_active", table_name="public_status_pages")
    op.drop_table("public_status_pages")
    # ### end Alembic commands ###
