"""Add user incident views tracking

Revision ID: fc8f47027f1b
Revises: 10c64b68ff24
Create Date: 2025-12-10 12:58:52.969273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc8f47027f1b"
down_revision: Union[str, None] = "10c64b68ff24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_incident_views",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("viewed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incident.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "incident_id", name="unique_user_incident_view"),
    )
    op.create_index(
        "idx_user_incident_views_composite",
        "user_incident_views",
        ["user_id", "viewed_at"],
        unique=False,
    )
    op.create_index(
        "idx_user_incident_views_incident_user",
        "user_incident_views",
        ["incident_id", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_incident_views_incident_id"),
        "user_incident_views",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_incident_views_user_id"),
        "user_incident_views",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_incident_views_user_id"), table_name="user_incident_views"
    )
    op.drop_index(
        op.f("ix_user_incident_views_incident_id"), table_name="user_incident_views"
    )
    op.drop_index(
        "idx_user_incident_views_incident_user", table_name="user_incident_views"
    )
    op.drop_index("idx_user_incident_views_composite", table_name="user_incident_views")
    op.drop_table("user_incident_views")
    # ### end Alembic commands ###
