"""Add color customization fields to app_settings

Revision ID: fd4bbc9bd573
Revises: cc40503cb931
Create Date: 2025-12-08 15:10:35.164587

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd4bbc9bd573"
down_revision: Union[str, None] = "cc40503cb931"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default values for SQLite compatibility
    op.add_column(
        "app_settings",
        sa.Column(
            "enable_custom_colors",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "primary_color",
            sa.String(length=7),
            nullable=False,
            server_default=sa.text("'#59bc87'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "primary_hover_color",
            sa.String(length=7),
            nullable=False,
            server_default=sa.text("'#45a676'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "primary_subtle_color",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'rgba(168, 255, 204, 0.15)'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "success_color",
            sa.String(length=7),
            nullable=False,
            server_default=sa.text("'#22c55e'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "success_bg_color",
            sa.String(length=7),
            nullable=False,
            server_default=sa.text("'#f0fdf4'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "danger_color",
            sa.String(length=7),
            nullable=False,
            server_default=sa.text("'#dc2626'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "danger_bg_color",
            sa.String(length=7),
            nullable=False,
            server_default=sa.text("'#fef2f2'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "warning_color",
            sa.String(length=7),
            nullable=False,
            server_default=sa.text("'#f59e0b'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "warning_bg_color",
            sa.String(length=7),
            nullable=False,
            server_default=sa.text("'#fffbeb'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "info_color",
            sa.String(length=7),
            nullable=False,
            server_default=sa.text("'#06b6d4'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "info_bg_color",
            sa.String(length=7),
            nullable=False,
            server_default=sa.text("'#ecfeff'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "unknown_color",
            sa.String(length=7),
            nullable=False,
            server_default=sa.text("'#6b7280'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "unknown_bg_color",
            sa.String(length=7),
            nullable=False,
            server_default=sa.text("'#f3f4f6'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "dark_primary_color",
            sa.String(length=7),
            nullable=True,
            server_default=sa.text("'#3b82f6'"),
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "dark_primary_hover_color",
            sa.String(length=7),
            nullable=True,
            server_default=sa.text("'#60a5fa'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_settings", "dark_primary_hover_color")
    op.drop_column("app_settings", "dark_primary_color")
    op.drop_column("app_settings", "unknown_bg_color")
    op.drop_column("app_settings", "unknown_color")
    op.drop_column("app_settings", "info_bg_color")
    op.drop_column("app_settings", "info_color")
    op.drop_column("app_settings", "warning_bg_color")
    op.drop_column("app_settings", "warning_color")
    op.drop_column("app_settings", "danger_bg_color")
    op.drop_column("app_settings", "danger_color")
    op.drop_column("app_settings", "success_bg_color")
    op.drop_column("app_settings", "success_color")
    op.drop_column("app_settings", "primary_subtle_color")
    op.drop_column("app_settings", "primary_hover_color")
    op.drop_column("app_settings", "primary_color")
    op.drop_column("app_settings", "enable_custom_colors")
    # ### end Alembic commands ###
